export const authConstants={
    LOGIN_REQUIEST:"LOGIN_REQUIEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT:REQUEST",
    LOGOUT_SUCCESS: "LOGOUT:SUCCESS",
    LOGOUT_FAILURE: "LOGOUT:FAILURE"
}
export const userConstants={
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
}